league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:OAUTH_PRIVATE_KEY)%'
        private_key_passphrase: '%env(resolve:OAUTH_PASSPHRASE)%'
        encryption_key: '%env(resolve:OAUTH_ENCRYPTION_KEY)%'
        access_token_ttl: P1D
        refresh_token_ttl: P1M
    resource_server:
        public_key: '%env(resolve:OAUTH_PUBLIC_KEY)%'
    scopes:
        available: ['webadminapi']
        default: ['webadminapi']
    persistence:
        doctrine:
            entity_manager: default
            table_prefix: oauth2_
    role_prefix: ROLE_OAUTH2_

when@test:
    league_oauth2_server:
        persistence:
            in_memory: null
